Repository dscnitrourkela/project-oregano, pull requests merged in 2021-07, with the labels that each got.

#34 Updates PR to PR Request for accessing secrets
  .github/workflows/lighthouse.yml
Labels: check-for-lighthouse

#35 Updates base ref and removes unwanted data
  .github/workflows/lighthouse.yml
Labels: check-for-lighthouse

#37 feat: add sponsor section
  src/components/FaqSection/Faq.components.jsx
  src/components/FaqSection/Faq.jsx
  src/components/SponsorsSection/.gitkeep
  src/components/SponsorsSection/SponserImg.jsx
  src/components/SponsorsSection/Sponsor.jsx
  src/components/SponsorsSection/SponsorHeading.jsx
  src/components/SponsorsSection/Sponsors.components.jsx
  src/components/TracksSection/Card.jsx
  src/components/TracksSection/Tracks.components.jsx
  src/components/TracksSection/Tracks.jsx
  src/components/index.js
  src/components/shared/SectionContainer.jsx
  src/pages/index.jsx
  static/sponsor.png
Labels: wip

#49 feat: Add Navbar | Separate for Desktop & Mobile
  src/components/marginals/Footer.jsx
  src/components/marginals/NavItems.jsx
  src/components/marginals/Navbar.jsx
  src/components/marginals/Navbar/DesktopNav.jsx
  src/components/marginals/Navbar/Menucontext.jsx
  src/components/marginals/Navbar/MobileNav.jsx
  src/components/marginals/Navbar/NavItems.jsx
  src/components/marginals/Navbar/nav.styles.jsx
  src/components/marginals/index.js
  src/components/shared/Layout.jsx
  src/components/shared/index.js
  src/pages/index.jsx
  src/pages/playground.jsx
Labels: wip

#44 feat: Add Contact Us Section
  src/components/FaqSection/Contact/Contact.jsx
  src/components/FaqSection/Contact/ContactStyles.jsx
  src/components/FaqSection/Contact/Form.jsx
  src/components/FaqSection/Contact/FormSubmit.jsx
  src/components/FaqSection/Contact/FormSuccess.jsx
  src/components/FaqSection/Contact/Validate.jsx
  src/components/FaqSection/styles.jsx
  src/components/shared/Typography/Heading5.jsx
  static/gmail.png
  yarn.lock
Labels: wip

#51 feat: Add Footer Section
  config/content/Footer.js
  config/content/index.js
  package.json
  src/components/marginals/Footer/Data.jsx
  src/components/marginals/Footer/Footer.jsx
  src/components/marginals/Footer/FooterCard.jsx
  src/components/marginals/Footer/styles.js
  src/components/marginals/index.js
  src/components/shared/SectionContainer.jsx
  src/components/shared/Typography/Heading4.jsx
  src/pages/index.jsx
  tailwind.config.js
  yarn.lock
Labels: wip

#64 feat: Add Scrolling In Navigation
  config/content/FAQ.js
  config/content/Navigation.js
  config/content/index.js
  package.json
  src/components/FaqSection/Faq.jsx
  src/components/HeroSection/HeroContent.jsx
  src/components/HeroSection/HeroSection.jsx
  src/components/SponsorsSection/Sponsor.jsx
  src/components/TracksSection/Tracks.jsx
  src/components/marginals/Footer/Footer.jsx
  src/components/marginals/Navbar/DesktopNav.jsx
  src/components/marginals/Navbar/MobileNav.jsx
  src/components/shared/Button.jsx
  src/components/shared/Layout.jsx
  src/components/shared/SectionLayout.jsx
  src/pages/index.jsx
  src/utils/scrollTo.js
  yarn.lock
Labels: ready-to-merge
